-- 1
ALTER TABLE DATOS_PERSONALES ADD CONSTRAINT CK_TIPO CHECK(TIPO IN ('N', 'D'));

-- 2
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT CK_NUM_PROF CHECK(NUM_PROF BETWEEN 1 AND 30);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT UC_DESCRIPCION UNIQUE(DESCRIPCION);

-- 3
ALTER TABLE DOCTORANDO ADD CONSTRAINT CK_FECHA_COMIENZO CHECK(FECHA_COMIENZO BETWEEN TO_DATE('1-1-2000') AND FECHA_ALTA);

-- 4
ALTER TABLE DOCTOR ADD CONSTRAINT UC_TITULO UNIQUE(TITULO);
ALTER TABLE DOCTOR ADD CONSTRAINT CK_TITULO CHECK(TITULO >= 10);
ALTER TABLE DOCTOR ADD CONSTRAINT CK_CALIFICACION CHECK(CALIFICACION BETWEEN 0 AND 10);

-- 5
ALTER TABLE CURSO ADD CONSTRAINT CK_DURACION CHECK(DURACION BETWEEN 10 AND 500);