-- 1
ALTER TABLE CURSO ADD CONSTRAINT FK_AULA FOREIGN KEY(COD_AULA) REFERENCES AULA(COD_AULA);

-- 2
ALTER TABLE DOCTORANDO ADD COD_CURSO NUMBER(4);
ALTER TABLE DOCTORANDO ADD CONSTRAINT FK_CURSO FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO);

-- 3
ALTER TABLE AULA ADD COLUMN TIPO VARCHAR('30');
ALTER TABLE AULA ADD CONSTRAINT CK_TIPO CHECK(TIPO IN ('Audiovisual', 'Grupos pequeños', 'Normal', 'Magna'));