CREATE TABLE SEDE(
    COD_SEDE NUMBER(4),
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_SEDE PRIMARY KEY(COD_SEDE)
);

CREATE TABLE DEPARTAMENTO(
    COD_DEP NUMBER(4),
    NOMBRE VARCHAR(30) NOT NULL,
    UBICACION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(COD_DEP)
);

CREATE TABLE PROGRAMADOR(
    COD_SEDE NUMBER(4),
    DNI_PROG VARCHAR(9),
    NOMBRE VARCHAR(40) NOT NULL,
    AP1 VARCHAR(40) NOT NULL,
    AP2 VARCHAR(40),
    DIRECCION VARCHAR(30) NOT NULL,
    CUENTA VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    TIPO NUMBER(1) NOT NULL,
    CONSTRAINT PK_PROGRAMADOR PRIMARY KEY(DNI_PROG, COD_SEDE),
);

-- Interrelación reflexiva (F · CodProgrMentor > Programador)
ALTER TABLE PROGRAMADOR ADD CONSTRAINT FK_COD_PROG_MENTOR FOREIGN KEY(COD_PROG_MENTOR, COD_DEP, COD_SEDE) REFERENCES PROGRAMADOR(DNI_PROG, COD_DEP, COD_SEDE);

CREATE TABLE EQUIPO(
    COD_DEP NUMBER(4),
    DESCRIPCION VARCHAR(30) NOT NULL,
    DNI_PROG VARCHAR(9) NOT NULL,
    CONSTRAINT PK_EQUIPO PRIMARY KEY(COD_DEP),
);

CREATE TABLE EQUIPO_PROG(
    DNI_PROG VARCHAR(9),
    COD_EQUIPO NUMBER(4),
    CONSTRAINT PK_EQUIPO_PROG PRIMARY KEY(DNI_PROG, COD_EQUIPO)
);

CREATE TABLE PROYECTO(
    COD_PROY NUMBER(4),
    DESCRIPCION VARCHAR(30) NOT NULL,
    FECHA_INI DATE,
    FECHA_FIN DATE,
    CONSTRAINT PK_PROYECTO PRIMARY KEY(COD_PROY),
);

-- Interrelación reflexiva (F · CodSubProy > Proyecto)
ALTER TABLE PROYECTO ADD CONSTRAINT FK_COD_SUB_PROY FOREIGN KEY(COD_SUB_PROY) REFERENCES PROYECTO(COD_EQUIPO, COD_PROY);