CREATE TABLE SEDE(
    COD_SEDE NUMBER(4),
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_SEDE PRIMARY KEY(COD_SEDE)
);

-- Departamento tiene Cod_Sede como clave foránea de Sede porque es débil en relación a ella
CREATE TABLE DEPARTAMENTO(
    COD_SEDE NUMBER(4),
    COD_DEP NUMBER(4),
    NOMBRE VARCHAR(30) NOT NULL,
    UBICACION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(COD_SEDE, COD_DEP),
    CONSTRAINT FK_COD_SEDE FOREIGN KEY(COD_SEDE) REFERENCES SEDE(COD_SEDE)
);

-- Programador tiene Cod_Dep como clave foránea de Departamento porque es débil en relación a Departamento, que a su vez es débil a Sede, por lo que también tiene la clave foránea Cod_Sede de Sede
CREATE TABLE PROGRAMADOR(
    COD_SEDE NUMBER(4),
    COD_DEP NUMBER(4),
    DNI_PROG VARCHAR(9),
    NOMBRE VARCHAR(40) NOT NULL,
    AP1 VARCHAR(40) NOT NULL,
    AP2 VARCHAR(40),
    DIRECCION VARCHAR(30) NOT NULL,
    CUENTA VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    TIPO NUMBER(1) NOT NULL,
    COD_PROG_MENTOR NUMBER(4) NOT NULL,
    CONSTRAINT PK_PROGRAMADOR PRIMARY KEY(DNI_PROG, COD_DEP, COD_SEDE),
    CONSTRAINT FK_COD_DEP FOREIGN KEY(COD_DEP, COD_SEDE) REFERENCES DEPARTAMENTO(COD_DEP, COD_SEDE)
);

ALTER TABLE PROGRAMADOR ADD CONSTRAINT FK_COD_PROG_MENTOR FOREIGN KEY(COD_PROG_MENTOR, COD_DEP, COD_SEDE) REFERENCES PROGRAMADOR(DNI_PROG, COD_DEP, COD_SEDE);

CREATE TABLE EQUIPO(
    COD_DEP NUMBER(4),
    DESCRIPCION VARCHAR(30) NOT NULL,
    DNI_PROG VARCHAR(9) NOT NULL,
    CONSTRAINT PK_EQUIPO PRIMARY KEY(COD_DEP),
    CONSTRAINT FK_DNI_PROG FOREIGN KEY(DNI_PROG) REFERENCES PROGRAMADOR(DNI_PROG)
);

CREATE TABLE EQUIPO_PROG(
    DNI_PROG VARCHAR(9),
    COD_EQUIPO NUMBER(4),
    CONSTRAINT PK_EQUIPO_PROG PRIMARY KEY(DNI_PROG, COD_EQUIPO),
    CONSTRAINT FK_DNI_PROG FOREIGN KEY(DNI_PROG) REFERENCES PROGRAMADOR(DNI_PROG),
    CONSTRAINT FK_COD_EQUIPO FOREIGN KEY(COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO)
);

-- Proyecto tiene Cod_Equipo como clave foránea de Equipo porque es débil en relación a esa tabla
CREATE TABLE PROYECTO(
    COD_EQUIPO NUMBER(4),
    COD_PROY NUMBER(4),
    DESCRIPCION VARCHAR(30) NOT NULL,
    FECHA_INI DATE,
    FECHA_FIN DATE,
    CONSTRAINT PK_PROYECTO PRIMARY KEY(COD_EQUIPO, COD_PROY),
    CONSTRAINT FK_COD_EQUIPO FOREIGN KEY(COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO)
);

ALTER TABLE PROYECTO ADD CONSTRAINT FK_COD_SUB_PROY FOREIGN KEY(COD_SUB_PROY) REFERENCES PROYECTO(COD_EQUIPO, COD_PROY);