CREATE TABLE OFICINA(
    COD_OFICINA NUMBER(4),
    DIRECCION VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    DNI_DIRECTOR VARCHAR(9) NOT NULL,
    DNI_COMERCIAL VARCHAR(9) NOT NULL,
    CONSTRAINT FK_DIRECTOR FOREIGN KEY DIRECTOR(DNI_DIRECTOR) ON DELETE CASCADE,
    CONSTRAINT CK_OFICINA CHECK(LENGTH(TELEFONO) = 9)
);

CREATE TABLE COMERCIAL(
    DNI NUMBER(4),
    COMISION NUMBER(2) NOT NULL,
    COD_OFICINA NUMBER(4) NOT NULL,
    CONSTRAINT PK_DNI PRIMARY KEY(DNI),
    CONSTRAINT FK_DATOS_PERSONALES FOREIGN KEY(DNI) REFERENCES DATOS_PERSONALES(DNI) ON DELETE CASCADE,
    CONSTRAINT FK_OFICINA FOREIGN KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA) ON DELETE CASCADE,
    CONSTRAINT CK_COMISION CHECK(COMISION > 0 AND COMISION < 100)
);

ALTER TABLE OFICINA ADD CONSTRAINT FK_COMERCIAL FOREIGN KEY(DNI_COMERCIAL) REFERENCES COMERCIAL(DNI) ON DELETE CASCADE;

CREATE TABLE VENDEDOR(
    DNI VARCHAR(9),
    TURNO VARCHAR(30),
    COD_OFICINA NUMBER(4),
    CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI),
    CONSTRAINT FK_DATOS_PERSONALES FOREIGN KEY(DNI) REFERENCES DATOS_PERSONALES(DNI) ON DELETE CASCADE,
    CONSTRAINT FK_OFICINA FOREIGN KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA) ON DELETE CASCADE
);