CREATE TABLE TIPO_DP(
    COD_TIPO NUMBER(4),
    DESCRIPCION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TIPO_DP PRIMARY KEY(COD_TIPO)
);

-- Pasar a nulos:
ALTER TABLE DATOS_PERSONALES MODIFY TELEFONO NUMBER(9);
ALTER TABLE DATOS_PERSONALES MODIFY CORREO VARCHAR(30);

ALTER TABLE DATOS_PERSONALES ADD TIPO VARCHAR(30);
ALTER TABLE DATOS_PERSONALES ADD CONSTRAINT FK_TIPO_DP FOREIGN KEY(TIPO) REFERENCES TIPO_DP(COD_TIPO);

ALTER TABLE DIRECTOR ADD ANIOS NUMBER(2);

ALTER TABLE COMERCIAL DROP COLUMN COMISION; -- / ALTER TABLE COMERCIAL DROP(COMISION)
-- DROP: Sobre las tablas
-- DELETE: Sobre la información de las tablas

ALTER TABLE OFICINA ADD COLUMN COMISION;

CREATE TABLE TURNO(
    COD_TURNO NUMBRE(4),
    DESCRPIPCION VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TURNO PRIMARY KEY(COD_TURNO)
);

ALTER TABLE VENDEDOR ADD TURNO VARCHAR(30);
ALTER TABLE VENDEDOR ADD CONSTRAINT FK_TURNO FOREIGN KEY(TURNO) REFERENCES TURNO(COD_TURNO);

CREATE TABLE TEMATICA_LIBRO(
    COD_TEM NUMBER(4),
    DESCRIPCION VARCHAR(40) NOT NULL
);

ALTER TABLE LIBRO RENAME TEMATICA TO COD_TEM;
ALTER TABLE LIBRO RENAME PRECIO TO PRECIO_ACTUAL;

ALTER TABLE LIBRO ADD CONSTRAINT FK_TEMATICA_LIBRO FOREIGN KEY(COD_TEM) REFERENCES TEMATICA_LIBRO(COD_TEM);